apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: cluster-1
  git:
    syncRepo: git@github.com:elatovg/anthos-conf-mgmt.git
    syncBranch: 0.1.0
    secretType: ssh
    policyDir: "configs"
